export { default as Hamburger } from '/public/icons/hamburger.svg';
export { default as ArrowDown } from '/public/icons/arrow-down.svg';
export { default as Github } from '/public/icons/github.svg';
export { default as LinkedIn } from '/public/icons/linkedin.svg';
export { default as Close } from '/public/icons/close.svg';
export { default as Portrait } from '/public/icons/portrait.svg';
export { default as ArrowSingleRight } from '/public/icons/arrow-single-right.svg';
export { default as ArrowRight } from '/public/icons/arrow-right.svg';
export { default as Gmail } from '/public/icons/gmail.svg';
