name: Run ESLint on Pull Requests

on:
    pull_request:
        branches: ['develop']

jobs:
    lint:
        name: Lint source code
        runs-on: ubuntu-latest
        steps:
            - name: Check out the source
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint the source
              run: pnpm run lint

            - name: Test the source
              run: pnpm run test

            - name: Build
              run: pnpm run build
